# Generated by Django 5.1 on 2024-11-03 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_ID', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_pass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_pass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('job_dept', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('ded_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ded_type', models.CharField(max_length=100)),
                ('ded_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_ID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.job')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('report', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.job')),
                ('leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.leave')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.salary')),
            ],
        ),
    ]
