# Generated by Django 5.1 on 2024-11-03 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction',
            old_name='employee',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='employee',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='employee',
            new_name='emp',
        ),
        migrations.AddField(
            model_name='payroll',
            name='ded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.deduction'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_pass',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='fname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='lname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='ded_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_pass',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_dept',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
