# Generated by Django 5.1 on 2024-11-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_employee_deduction_emp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_pass',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_email',
            new_name='username',
        ),
    ]
